export const cropsData = [
    { id: "rice", name: "Rice/Paddy", botanicalName: "Oryza sativa", npk: { n: 120, p: 60, k: 60 }, image: "/images/rice.webp" },
    { id: "wheat", name: "Wheat", botanicalName: "Triticum aestivum", npk: { n: 120, p: 60, k: 40 }, image: "/images/wheat.webp" },
    { id: "cotton", name: "Cotton", botanicalName: "Gossypium spp.", npk: { n: 150, p: 75, k: 75 }, image: "/images/cotton.jpg" },
    { id: "sugarcane", name: "Sugarcane", botanicalName: "Saccharum officinarum", npk: { n: 250, p: 100, k: 125 }, image: "/images/sugarcane.webp" },
    { id: "maize", name: "Maize/Corn", botanicalName: "Zea mays", npk: { n: 150, p: 75, k: 50 }, image: "/images/maize.webp" },
    { id: "potato", name: "Potato", botanicalName: "Solanum tuberosum", npk: { n: 180, p: 100, k: 150 }, image: "/images/potato.webp" },
    { id: "tomato", name: "Tomato", botanicalName: "Solanum lycopersicum", npk: { n: 150, p: 100, k: 120 }, image: "/images/tomato.jpeg" },
    { id: "onion", name: "Onion", botanicalName: "Allium cepa", npk: { n: 120, p: 80, k: 100 }, image: "/images/oninon.webp" },
    { id: "barley", name: "Barley", botanicalName: "Hordeum vulgare", npk: { n: 90, p: 40, k: 30 }, image: "/images/barley.webp" },
    { id: "soybean", name: "Soybean", botanicalName: "Glycine max", npk: { n: 30, p: 60, k: 40 }, image: "/images/soyabean.webp" },
    { id: "groundnut", name: "Groundnut", botanicalName: "Arachis hypogaea", npk: { n: 30, p: 60, k: 45 }, image: "/images/groundnut.webp" },
    { id: "sunflower", name: "Sunflower", botanicalName: "Helianthus annuus", npk: { n: 80, p: 60, k: 40 }, image: "/images/sunflower.webp" },
    { id: "chickpea", name: "Chickpea", botanicalName: "Cicer arietinum", npk: { n: 20, p: 50, k: 25 }, image: "/images/chickpea.webp" },
    { id: "mustard", name: "Mustard", botanicalName: "Brassica juncea", npk: { n: 100, p: 50, k: 40 }, image: "/images/mustrud.webp" },
    { id: "peas", name: "Peas", botanicalName: "Pisum sativum", npk: { n: 25, p: 60, k: 50 }, image: "/images/peas.webp" },
    { id: "lentil", name: "Lentil", botanicalName: "Lens culinaris", npk: { n: 20, p: 40, k: 20 }, image: "/images/lentil.webp" },
    { id: "blackgram", name: "Black Gram", botanicalName: "Vigna mungo", npk: { n: 20, p: 40, k: 20 }, image: "/images/blackgram.webp" },
    { id: "greengram", name: "Green Gram", botanicalName: "Vigna radiata", npk: { n: 20, p: 40, k: 20 }, image: "/images/greengram.webp" },
    { id: "kidneybean", name: "Kidney Bean", botanicalName: "Phaseolus vulgaris", npk: { n: 30, p: 60, k: 40 }, image: "/images/kidneybean.webp" },
    { id: "pigeonpea", name: "Pigeon Pea", botanicalName: "Cajanus cajan", npk: { n: 25, p: 50, k: 25 }, image: "/images/pegionpea.webp" },
    { id: "banana", name: "Banana", botanicalName: "Musa spp.", npk: { n: 200, p: 60, k: 400 }, image: "/images/banana.webp" },
    { id: "mango", name: "Mango", botanicalName: "Mangifera indica", npk: { n: 250, p: 125, k: 250 }, image: "/images/Mango.webp" },
    { id: "coconut", name: "Coconut", botanicalName: "Cocos nucifera", npk: { n: 500, p: 320, k: 1200 }, image: "/images/coconut.webp" },
    { id: "papaya", name: "Papaya", botanicalName: "Carica papaya", npk: { n: 250, p: 250, k: 500 }, image: "/images/papaya.webp" },
    { id: "apple", name: "Apple", botanicalName: "Malus domestica", npk: { n: 150, p: 75, k: 150 }, image: "/images/apple.webp" },
    { id: "grapes", name: "Grapes", botanicalName: "Vitis vinifera", npk: { n: 150, p: 100, k: 200 }, image: "/images/grapes.webp" }
];

export const fertilizerData = [
    { id: "urea", name: "Urea (46-0-0)", n: 46, p: 0, k: 0, bagWeight: 45, price: 266.5 },
    { id: "dap", name: "DAP (18-46-0)", n: 18, p: 46, k: 0, bagWeight: 50, price: 1350 },
    { id: "mop", name: "MOP (0-0-60)", n: 0, p: 0, k: 60, bagWeight: 50, price: 1710 },
    { id: "npk_10_26_26", name: "NPK Complex (10-26-26)", n: 10, p: 26, k: 26, bagWeight: 50, price: 1815 },
    { id: "npk_12_32_16", name: "NPK Complex (12-32-16)", n: 12, p: 32, k: 16, bagWeight: 50, price: 1712 },
    { id: "npk_20_20_0", name: "NPK Complex (20-20-0)", n: 20, p: 20, k: 0, bagWeight: 50, price: 1100 },
    { id: "npk_17_17_17", name: "NPK Complex (17-17-17)", n: 17, p: 17, k: 17, bagWeight: 50, price: 1300 },
    { id: "ssp", name: "SSP (0-16-0)", n: 0, p: 16, k: 0, bagWeight: 50, price: 350 },
    { id: "ammonium_sulphate", name: "Ammonium Sulphate (21-0-0)", n: 21, p: 0, k: 0, bagWeight: 50, price: 600 },
    { id: "rock_phosphate", name: "Rock Phosphate (0-30-0)", n: 0, p: 30, k: 0, bagWeight: 50, price: 500 },
    { id: "potassium_sulphate", name: "Potassium Sulphate (0-0-50)", n: 0, p: 0, k: 50, bagWeight: 50, price: 1200 },
    { id: "bio_fertilizer", name: "Bio Fertilizer (3-1-2)", n: 3, p: 1, k: 2, bagWeight: 50, price: 700 },
    { id: "vermicompost", name: "Vermicompost (1.5-0.5-1)", n: 1.5, p: 0.5, k: 1, bagWeight: 50, price: 300 },
    { id: "neem_cake", name: "Neem Cake (5-1-1.5)", n: 5, p: 1, k: 1.5, bagWeight: 50, price: 900 },
    { id: "bone_meal", name: "Bone Meal (3-15-0)", n: 3, p: 15, k: 0, bagWeight: 50, price: 850 },
    { id: "green_manure", name: "Green Manure (2.5-1.5-1.8)", n: 2.5, p: 1.5, k: 1.8, bagWeight: 50, price: 250 },
    { id: "cow_dung", name: "Cow Dung Manure (0.5-0.3-0.4)", n: 0.5, p: 0.3, k: 0.4, bagWeight: 50, price: 200 },
    { id: "poultry_litter", name: "Poultry Litter (3-2.5-1.5)", n: 3, p: 2.5, k: 1.5, bagWeight: 50, price: 300 }
];